netSingin:
  path:     /
  host:     "{subdomain}.{domain}"
  defaults: { _controller: '\Ubirimi\FrontendNET\Controller\SigninController' }
  requirements:
    domain: ubirimi_net.lan|ubirimi.net
    subdomain: .*

netSingout:
  path:     /sign-out
  host:     "{subdomain}.{domain}"
  defaults: { _controller: '\Ubirimi\FrontendNET\Controller\SignoutController' }
  requirements:
    domain: ubirimi_net.lan|ubirimi.net
    subdomain: .*

netSignup:
  path:     /sign-up
  host:     "{subdomain}.{domain}"
  defaults: { _controller: '\Ubirimi\FrontendNET\Controller\SignupController' }
  requirements:
    domain: ubirimi_net.lan|ubirimi.net
    subdomain: .*

netRecoverPassword:
  path:     /recover-password
  host:     "{subdomain}.{domain}"
  defaults: { _controller: '\Ubirimi\FrontendNET\Controller\PasswordRecoverController' }
  requirements:
    domain: ubirimi_net.lan|ubirimi.net
    subdomain: .*

netRecoverPasswordDO:
  path:     /recover-password/do
  host:     "{subdomain}.{domain}"
  defaults: { _controller: '\Ubirimi\FrontendNET\Controller\PasswordRecoverDoController' }
  requirements:
    domain: ubirimi_net.lan|ubirimi.net
    subdomain: .*

netSetupPayment:
  path:     /setup-payment
  host:     "{subdomain}.{domain}"
  defaults: { _controller: '\Ubirimi\FrontendNET\Controller\SetupPaymentController' }
  requirements:
    domain: ubirimi_net.lan|ubirimi.net
    subdomain: .*