comHome:
  path: /
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\IndexController' }

comProductYongo:
  path: /product/yongo
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Product\YongoController' }

comProductAgile:
  path: /product/agile
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Product\AgileController' }

comProductHelpdesk:
  path: /product/helpdesk
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Product\HelpdeskController' }

comProductSVN:
  path: /product/svn-hosting
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Product\SVNHostingController' }

comProductDocumentador:
  path: /product/documentador
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Product\DocumentadorController' }

comProductEvents:
  path: /product/events
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Product\EventsController' }

comProducts:
  path: /products
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Product\ListController' }

comPricing:
  path: /pricing
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\PricingController' }

comCompany:
  path: /company
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\CompanyController' }

comSignout:
  path: /sign-out
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\SignoutController' }

comSignin:
  path: /sign-in
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\SigninController' }

comContact:
  path: /contact
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\ContactController' }

comContactSend:
  path: /contact/send
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\ContactSendController' }

comAccountHome:
  path: /account/home
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Account\HomeController' }

comAccountProfile:
  path: /account/profile
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Account\ProfileController' }

comAccountProfileSave:
  path: /account/profile/save
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Account\ProfileSaveController' }

comPaymentView:
  path: /account/pay
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Account\Payment\PayController' }

comAccountSettings:
  path: /account/settings
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Account\SettingsController' }

comAccountSettingsDelete:
  path: /account/settings/delete
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Account\DeleteController' }

comPaymentProcess:
  path: /account/payment/process
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Account\Payment\ProcessController' }
  methods:  [POST]

comPaymentInvoices:
  path: /account/invoices
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Account\Payment\InvoiceController' }
  methods:  [GET]

comPaymentBilling:
  path: /account/billing
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Account\BillingController' }
  methods:  [GET]

comPaymentBillingUpdate:
  path: /account/billing/update
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Account\BillingUpdateController' }

comPaymentBillingUpdateDo:
  path: /account/billing/update/do
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Account\BillingUpdateDoController' }

comPrivacy:
  path: /privacy
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\PrivacyController' }

comTermsOfUse:
  path: /terms-of-service
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\TermsOfServiceController' }

comSubscribeNewsletter:
  path: /subscribe-newsletter
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\SubscribeNewsletterController' }

comSubscribeNewsletterDone:
  path: /subscribe-newsletter-done
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\SubscribeNewsletterDoneController' }

comRecoverPssword:
  path: /recover-password
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\PasswordRecoverController' }

comRecoverPasswordDo:
  path: /recover-password/do
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\PasswordRecoverDoController' }

comBlog:
  path: /blog/{blog_page}
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\BlogController', blog_page: null }

comSignup:
  path: /sign-up
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\SignupController' }

comSignupSuccess:
  path: /sign-up-success
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\SignupSuccessController' }

comAdministrationIndex:
  path: /administration
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\IndexController' }

comAdminActiveClients:
  path: /administration/active-clients
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\ActiveClientsController' }

comAdminClients:
  path: /administration/clients
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\ClientsController' }

comAdminProjects:
  path: /administration/projects
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\ProjectsController' }

comAdminUsers:
  path: /administration/users
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\UsersController' }

comAdminSVN:
  path: /administration/svn
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\SVNController' }

comAdminIssues:
  path: /administration/issues
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\IssueController' }

comAdminAgileBoard:
  path: /administration/agile-boards
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\AgileBoardController' }

comAdminAgileSprints:
  path: /administration/agile-sprints
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\AgileSprintController' }

comAdminSpaces:
  path: /administration/spaces
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\SpaceController' }

comAdminEntity:
  path: /administration/entities
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\EntityController' }

comAdminMailQueue:
  path: /administration/mail-queue
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\MailQueueController' }

comAdminCalendar:
  path: /administration/calendars
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\CalendarController' }

comAdminApacheLogs:
  path: /administration/apache-logs
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\ApacheLogsController' }

comAdminLog:
  path: /administration/logs
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\LogController' }

comAdminReleaseVersion:
  path: /administration/release-version
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\ReleaseVersionController' }

comAdminMaintenance:
  path: /administration/maintenance
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\MaintenanceController' }

comAdminDeleteClient:
  path: /administration/client/delete
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\DeleteClientController' }

comAdminUpdateDB:
  path: /administration/update-bd
  defaults: { _controller: '\Ubirimi\FrontendCOM\Controller\Administration\UpdateDatabaseController' }
