apiIssueGET:
  path: /api/issue/{id}
  defaults: { _controller: '\Ubirimi\Api\Controller\Issue\GetController' }
  methods:  [GET]
  requirements:
    id:  \d+

apiProjectGET:
  path: /api/project/{code}
  defaults: { _controller: '\Ubirimi\Api\Controller\Project\GetController' }
  methods:  [GET]

apiUserGET:
  path: /api/user/{username}
  defaults: { _controller: '\Ubirimi\Api\Controller\User\GetController' }
  methods:  [GET]