apiIssueGET:
  path: /api/issue/{id}
  defaults: { _controller: '\Ubirimi\Api\Controller\Issue\GetController' }
  methods:  [GET]
  requirements:
    id:  \d+

apiIssuePOST:
  path: /api/issue
  defaults: { _controller: '\Ubirimi\Api\Controller\Issue\PostController' }
  methods:  [POST]

apiIssueMetadataGET:
  path: /api/issue/metadata
  defaults: { _controller: '\Ubirimi\Api\Controller\Issue\MetadataController' }
  methods:  [GET]

apiProjectGET:
  path: /api/project/{code}
  defaults: { _controller: '\Ubirimi\Api\Controller\Project\GetController' }
  methods:  [GET]

apiUserGET:
  path: /api/user/{username}
  defaults: { _controller: '\Ubirimi\Api\Controller\User\GetController' }
  methods:  [GET]

apiUserAuthenticate:
  path: /api/user/authenticate
  defaults: { _controller: '\Ubirimi\Api\Controller\User\AuthenticateController' }
  methods:  [POST]

apiInstallClient:
  path: /api/client/save
  defaults: { _controller: '\Ubirimi\Api\Controller\Client\SaveController' }
  methods:  [POST]

apiClientUpdateProfile:
  path: /api/client/update/profile
  defaults: { _controller: '\Ubirimi\Api\Controller\Client\UpdateProfileController' }
  methods:  [POST]

apiGetClient:
  path: /api/client/{id}
  defaults: { _controller: '\Ubirimi\Api\Controller\Client\GetController' }
  methods:  [GET]
  requirements:
    id:  \d+

apiGetPaymentAmountByCountUsers:
  path: /api/payment/{client_id}
  defaults: { _controller: '\Ubirimi\Api\Controller\Payment\GetController' }
  methods:  [GET]
  requirements:
    client_id:  \d+
